"""Constants for challenge, standard and hardcore leagues metadata."""

CHALLENGE_LEAGUE_NAME = "Affliction"
"""Current challenge league name"""
CHALLENGE_LEAGUE_HC_NAME = f"Hardcore {CHALLENGE_LEAGUE_NAME}"
"""Current challenge hardcore league name"""
CHALLENGE_LEAGUE_SSF_NAME = f"SSF {CHALLENGE_LEAGUE_NAME}"
"""Current challenge solo self-found league name"""
CHALLENGE_LEAGUE_HC_SSF_NAME = f"HC SSF {CHALLENGE_LEAGUE_NAME}"
"""Current challenge hardcore solo self-found league name"""
STANDARD_LEAGUE_NAME = "Standard"
"""'Standard' league name"""
HARDCORE_LEAGUE_NAME = "Hardcore"
"""'Standard Hardcore' league name"""
