TEMPORARY_LEAGUE_NAME = "Kalandra"
TEMPORARY_LEAGUE_URL = "challenge"
TEMPORARY_LEAGUE_DISPLAY_NAME = TEMPORARY_LEAGUE_NAME

TEMPORARY_LEAGUE_HC_NAME = "Hardcore " + TEMPORARY_LEAGUE_NAME
TEMPORARY_LEAGUE_HC_URL = TEMPORARY_LEAGUE_URL + "hc"
TEMPORARY_LEAGUE_HC_DISPLAY_NAME = "HC " + TEMPORARY_LEAGUE_NAME

TEMPORARY_LEAGUE_SSF_NAME = "SSF " + TEMPORARY_LEAGUE_NAME
TEMPORARY_LEAGUE_SSF_URL = TEMPORARY_LEAGUE_URL + "ssf"
TEMPORARY_LEAGUE_SSF_DISPLAY_NAME = TEMPORARY_LEAGUE_SSF_NAME

TEMPORARY_LEAGUE_HC_SSF_NAME = "SSF " + TEMPORARY_LEAGUE_NAME + " HC"
TEMPORARY_LEAGUE_HC_SSF_URL = TEMPORARY_LEAGUE_URL + "hcssf"
TEMPORARY_LEAGUE_HC_SSF_DISPLAY_NAME = TEMPORARY_LEAGUE_HC_SSF_NAME

STANDARD_LEAGUE_NAME = "Standard"
STANDARD_LEAGUE_URL = "standard"
STANDARD_LEAGUE_DISPLAY_NAME = STANDARD_LEAGUE_NAME

HARDCORE_LEAGUE_NAME = "Hardcore"
HARDCORE_LEAGUE_URL = "hardcore"
HARDCORE_LEAGUE_DISPLAY_NAME = HARDCORE_LEAGUE_NAME
