# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and lint the code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install pip, Poetry and dependencies
      run: |
        python -m pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
    - name: Lint PyPoeNinja code with Ruff
      run: |
        poetry run ruff ./pypoeninja
    - name: Lint tests with Ruff
      run: |
        poetry run ruff ./tests
    - name: Lint project with mypy
      run: |
        poetry run mypy .
    - name: Lint PyPoeNinja code with pylint
      run: |
        poetry run pylint ./pypoeninja/**/*.py
    - name: Lint tests with pylint
      run: |
        poetry run pylint ./tests/**/*.py
    - name: Run tests
      run: |
        poetry run pytest
